#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/numakiti -a -d /usr/share/doc/numakiti ]; then
		ln -sf ../share/doc/numakiti /usr/doc/numakiti
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" -a -x /usr/bin/update-menus ]; then update-menus ; fi
# End automatically added section
